name: Daily Morning Post - Yesterday's Top Products

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run without posting to Twitter'
        required: false
        default: false
        type: boolean
  schedule:
    - cron: "5 8 * * *" # Daily at 00:05 Pacific Time (08:05 UTC)

env:
  REACT_APP_PRODUCT_HUNT_API_KEY: ${{ secrets.REACT_APP_PRODUCT_HUNT_API_KEY }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  render:
    name: Build and Post Yesterday's Products
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: mkdir -p data
      
      # Cache pnpm dependencies
      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT
      
      - uses: actions/cache@v4
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      
      - run: pnpm install --frozen-lockfile
      - name: Create placeholder midday.json for webpack
        run: |
          echo '{"date": "", "products": []}' > data/midday.json
      - run: pnpm run fetch:yesterday
      - name: Verify data file exists
        run: |
          if [ ! -f data/yesterday.json ]; then
            echo "Error: data/yesterday.json not found after fetch"
            exit 1
          fi
      - name: Build video for GitHub Actions
        run: pnpm run build:yesterday:ci
      - name: Post to Twitter
        if: ${{ !inputs.dry_run }}
        run: pnpm post-tweet
      - name: Skip Twitter post (dry run)
        if: ${{ inputs.dry_run }}
        run: echo "Dry run mode - skipping Twitter post"
      - uses: actions/upload-artifact@v4
        with:
          name: yesterday-video.mp4
          path: out/yesterday-video.mp4
