name: Tweet Daily Video

on:
  workflow_dispatch:
  schedule:
    - cron: "5 8 * * *" # Daily (00:05 every day in Pacific Timezone)

env:
  REACT_APP_PRODUCT_HUNT_API_KEY: ${{ secrets.REACT_APP_PRODUCT_HUNT_API_KEY }}
  TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
  TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
  TWITTER_ACCESS_TOKEN_KEY: ${{ secrets.TWITTER_ACCESS_TOKEN_KEY }}
  TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}

jobs:
  render:
    name: Tweet Daily Video
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
      - uses: pnpm/action-setup@v4
        with:
          version: 10.13.1
      - run: sudo apt update
      - run: sudo apt install ffmpeg
      - run: mkdir -p data
      - run: pnpm install --frozen-lockfile
      - run: pnpm run fetch:yesterday
      - name: Verify data file exists
        run: |
          if [ ! -f data/yesterday.json ]; then
            echo "Error: data/yesterday.json not found after fetch"
            exit 1
          fi
      - run: pnpm run build:yesterday
      - run: pnpm post-tweet
      - uses: actions/upload-artifact@v4
        with:
          name: yesterday-video.mp4
          path: out/yesterday-video.mp4
